Controllers/WaybillController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Triton.BusinessOnline.Models;
using Triton.Interface.BusinessOnline;
using Triton.Interface.CRM;
using Triton.Interface.Waybill;
using Triton.Model.CRM.Custom;
using Triton.Core;
using Triton.Interface.Documents;
using Triton.Interface.TritonGroup;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Triton.Model.CRM.Tables;
using WaybillSearchModel = Triton.BusinessOnline.Models.WaybillSearchModel;

namespace Triton.BusinessOnline.Controllers
{
    [Authorize]
    public class WaybillController : Controller
    {
        private readonly IBusinessOnline _boService;
        private readonly IWaybill _waybillService;
        private readonly ITransportTypes _transportTypeService;
        private readonly IUserMap _userMapService;
        private readonly IDocuments _documents;
        private readonly IWaybillAPI _waybillApi;
        private readonly IWaybillQueryMaster _waybillQueryMaster;
        private readonly ILookUpCodes _lookUpCodes;


        public WaybillController(IBusinessOnline boService, IWaybill waybillService, ITransportTypes transportTypeService, IUserMap userMapService, IWaybillAPI waybillApi, IDocuments documents, IWaybillQueryMaster waybillQueryMaster, ILookUpCodes lookUpCodes)
        {
            _waybillService = waybillService;
            _boService = boService;
            _transportTypeService = transportTypeService;
            _userMapService = userMapService;
            _waybillApi = waybillApi;
            _documents = documents;
            _waybillQueryMaster = waybillQueryMaster;
            _lookUpCodes = lookUpCodes;
        }

        public async Task<IActionResult> Search()
        {
            var model = new WaybillSearchModel
            {
                WaybillSearchItemList = await _lookUpCodes.GetTritonGroupLookUpCodesByLookupcodeIDs("431,432")
            };
            return View(model);
        }

        public async Task<IActionResult> Info(long waybillId)
        {
            try
            {
                var model = await _waybillService.GetWaybillInfoById(waybillId);
                if (model != null) return View(model);

                ViewData["Header"] = "Waybill not <span class='font-weight-semi-bold'>found</span>";
                ViewData["Message"] = "Sorry we could not find the waybill details";
            }
            catch
            {
                ViewData["Header"] = "Waybill not <span class='font-weight-semi-bold'>found</span>";
                ViewData["Message"] = "Sorry we could not find the waybill details";
            }

            return View("~/Views/Shared/Error.cshtml");
        }

        public async Task<IActionResult> WaybillListCategory(string customerId, string type, int totalWaybills)
        {
            var model = new WaybillCategoryModel
            {
                WaybillInfo = await _boService.GetCustomerDeliveriesByStatus(customerId, type),
                Category = type,
                TotalWaybills = totalWaybills
            };

            model.DeliveredPerc = (int)((double)model.WaybillInfo.Count / totalWaybills * 100);
            model.OutstandingPerc = 100 - model.DeliveredPerc;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Search(WaybillSearchModel wayBillmodel)
        {
            try
            {
                var waybillNo = "";
                var customerXRef = "";
                int? waybillId = null;

                if (wayBillmodel.LookUpCodeID == "431")
                {
                    waybillNo = wayBillmodel.SearchText;
                    customerXRef = null;
                }
                else if (wayBillmodel.LookUpCodeID == "432")
                {
                    waybillNo = null;
                    customerXRef = wayBillmodel.SearchText;
                }

                var model = new WaybillSearchModel
                {
                    VwOpsWaybill = await _waybillService.GetWaybillViewList(User.GetCustomerIds(), waybillNo, customerXRef, waybillId),
                    WaybillSearchItemList = await _lookUpCodes.GetTritonGroupLookUpCodesByLookupcodeIDs("431,432"),
                    ShowReport = true
                };

                model.WaybillStatusTypes = from b in await _waybillService.GetWaybillViewList(User.GetCustomerIds(), waybillNo, customerXRef, waybillId)
                                           group b by b.WaybillStatus into g
                                           select g.First();

                switch (model.VwOpsWaybill.Count)
                {
                    case 0:
                        // No Records Found
                        ModelState.AddModelError("CustomError", "No Records Found");
                        return View(model);
                    case 1:
                        // ReSharper disable once PossibleNullReferenceException
                        return RedirectToAction("Info", new { waybillId = model.VwOpsWaybill.FirstOrDefault().WaybillID });
                    default:
                        return View(model);
                }
            }

            catch (HttpRequestException e)
            {
                ModelState.AddModelError("error", e.Message);
                ViewData["Header"] = "Waybill not <span class='font-weight-semi-bold'>found</span>";
                ViewData["Message"] = "Sorry we could not find the waybill details";
                return View("~/Views/Shared/Error.cshtml");
            }
        }


        public async Task<IActionResult> SaveQuery(long waybillId, string query, int queryStatusLcid)
        {
            try
            {
                var model = new WaybillQueryMasterInsertModel
                {
                    Query = query,
                    WaybillId = waybillId,
                    CreatedByUserId = User.GetUserId(),
                    QueryStatusLcid = queryStatusLcid,
                    Resolution = null,
                    SystemId = 0,
                    UserId = User.GetUserId()
                };


                var result = await _waybillQueryMaster.PostWaybillQueryMaster(model);
                if (result)
                {
                    ViewData["Message"] = HtmlHelpers.Success;
                    var waybillModel = await _waybillService.GetWaybillInfoById(waybillId);
                    if (waybillModel != null) return View("Info", waybillModel);
                }
            }
            catch
            {
                ViewData["Header"] = "Waybill not <span class='font-weight-semi-bold'>found</span>";
                ViewData["Message"] = "Sorry we could not find the waybill details";
            }

            return View("~/Views/Shared/Error.cshtml");
        }

        public async Task<IActionResult> DeleteWaybillQuery(long waybillId)
        {
            try
            {
                var result = await _waybillQueryMaster.Delete(waybillId, User.GetUserId());
                if (result)
                {
                    ViewData["Message"] = HtmlHelpers.Success;
                    var waybillModel = await _waybillService.GetWaybillInfoById(waybillId);
                    if (waybillModel != null) return View("Info", waybillModel);
                }
            }
            catch
            {
                ViewData["Header"] = "Waybill not <span class='font-weight-semi-bold'>found</span>";
                ViewData["Message"] = "Sorry we could not find the waybill details";
            }

            return View("~/Views/Shared/Error.cshtml");
        }

        public async Task<ActionResult> PrintWaybillSticker(string waybillNo)
        {
            var x = await _waybillApi.GetStickersForWaybillasPDF(waybillNo);

            var cd = new System.Net.Mime.ContentDisposition
            {
                FileName = $"StickersFor{waybillNo}.pdf",
                Inline = false,
            };

            return File(x.ImgData, "application/pdf");
        }

        public async Task<ActionResult> PrintWaybillPODSticker(string waybillNo)
        {
            var x = await _waybillApi.GetPODStickersForWaybillasPDF(waybillNo);

            //var cd = new System.Net.Mime.ContentDisposition
            //{
            //    FileName = $"PODStickersFor{waybillNo}.pdf",
            //    Inline = false,
            //};

            return File(x.ImgData, "application/pdf", $"PODStickersFor{waybillNo}.pdf");
        }

        public async Task<ActionResult> PrintEWaybill(string waybillNo)
        {
            var x = await _waybillApi.GetEWaybillasPDF(waybillNo);

            var cd = new System.Net.Mime.ContentDisposition
            {
                FileName = $"{waybillNo}.pdf",
                Inline = false,
            };
            return File(x.ImgData, "application/pdf");
        }


        public async Task<ActionResult> PrintWaybillPOD(string waybillNo, string NodeName = "Final")
        {
            var x = await _waybillApi.GetWaybillPODImage(waybillNo, NodeName);
            var cd = new System.Net.Mime.ContentDisposition
            {
                FileName = $"{waybillNo}.pdf",
                Inline = false,
            };
            return File(x, "application/pdf");
        }

        public async Task<ActionResult> PrintSignature(string waybillNo)
        {
            try
            {
                var x = await _waybillApi.GetWaybillSignature(waybillNo);
                if (x != null)
                {
                    var cd = new System.Net.Mime.ContentDisposition
                    {
                        FileName = $"Signature.jpg",
                        Inline = false,
                    };
                    return File(x.Signature, "image/jpg");
                }

Views/Shared/CustomError.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

@{
    ViewData["Title"] = "Triton Express Error";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var template = $"{Configuration.GetSection("URL").GetSection("template").Value}";
}

<!-- ========== MAIN ========== -->
<main id="content" role="main" class="main">
    <div class="container">
        <img src="~/front-dashboard-v1.1/dist/assets/svg/illustrations/error-404.svg" class="formClass" />
        <h1 id="NoCustomers">@Html.Raw(ViewData["Heading"])</h1>
        <span id="ErrorMessage">@Html.Raw(ViewData["ErrorMessage"])</span>
    </div>
</main>
<!-- ========== END MAIN ========== -->

<style>
    .container img {
        width: 100%;
        height: auto;
    }

    .container #NoCustomers {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        color: black;
        padding: 12px 24px;
        border: none;
        cursor: pointer;
        text-align: center;
    }

    .container #ErrorMessage {
        position: absolute;
        top: 50%;
        left: 50%;
        margin-top: 60px;
        transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        color: black;
        font-size: 16px;
        padding: 12px 24px;
        border: none;
        cursor: pointer;
        text-align: center;
    }
</style>

Views/Shared/_HeaderPartial.cshtml
<div class="bg-light">
    <div class="container space-1">
        <div class="mb-3">
            <h1 class="h3 text-primary font-weight-normal mb-0">@ViewData["Header"] <span class="font-weight-semi-bold"> @ViewData["HeaderBold"]</span></h1>
            <p>
                @ViewData["Description"]
                @if (ViewData["WaybillActions"] != null)
                {
                    <div class="d-flex justify-content-between align-items-center">
                        <h4 class="h6 mb-0">&nbsp;</h4>
                        <!-- Settings Dropdown -->
                        <div class="position-relative">
                            <button id="activitySettingsDropdownInvoker" class="btn btn-sm btn-soft-secondary transition-3d-hover" type="button" aria-controls="activitySettingsDropdown" aria-haspopup="true" aria-expanded="false" data-unfold-event="click" data-unfold-target="#activitySettingsDropdown" data-unfold-type="css-animation" data-unfold-duration="300" data-unfold-delay="300" data-unfold-hide-on-scroll="true" data-unfold-animation-in="slideInUp" data-unfold-animation-out="fadeOut">
                                Actions <span class="fas fa-chevron-down text-right"></span>
                            </button>

                            <div id="activitySettingsDropdown" class="dropdown-menu dropdown-unfold dropdown-menu-right u-unfold--css-animation u-unfold--hidden" aria-labelledby="activitySettingsDropdownInvoker" style="min-width: 190px; animation-duration: 300ms; right: 0px;">
                                <a class="dropdown-item" href='#QueryModal' data-modal-target='#QueryModal'>
                                    <small class="fas fa-question-circle dropdown-item-icon"></small>
                                    Query this waybill
                                </a>
                                <a class="dropdown-item" href="@Url.Action("SaveQuery", "Waybill", new { waybillId = Model.Waybills.WaybillID, query = "Added to watch list", queryStatusLcid = 252 })">
                                    <small class="fas fa-eye dropdown-item-icon"></small>
                                    Add to watch list
                                </a>
                                <a class="dropdown-item" href="@Url.Action("DeleteWaybillQuery", "Waybill", new { waybillId = ViewData["waybillId"] })">
                                    <small class="fas fa-trash dropdown-item-icon"></small>
                                    Remove from watch list
                                </a>
                            </div>
                        </div>
                        <!-- End Settings Dropdown -->
                    </div>
                }
            </p>
        </div>
    </div>
</div>

Views/Shared/_LayoutMenu.cshtml
@using System.IO
@using System.Security.Claims
@using System.Xml.Linq
@using Microsoft.Extensions.Configuration
@using Triton.BusinessOnline.Areas.Identity.Pages.Account
@inject IConfiguration Configuration
@*@{
        var template = $"{Configuration.GetSection("URL").GetSection("template").Value}";

        var role = User.FindFirst(ClaimTypes.Role)?.Value;
        const string node = "mvcSiteMapNode";

        var xElement = XElement.Load($"{Directory.GetCurrentDirectory()}/Sitemap.xml");

        var siteMap = from xml in xElement.Elements(node)
                      where xml.Element(node)?.Attribute("roles") == null || xml.Element(node).Attribute("roles").ToString().Trim().Contains(role)
                      select xml;

        var dictionary = new Dictionary<LoginModel.ParentMenu, List<LoginModel.SubMenu>>();

        foreach (var site in siteMap)
        {
            var parentMenu = new LoginModel.ParentMenu();
            parentMenu.Title = site.Attribute("title")?.Value;
            parentMenu.Icon = site.Attribute("icon")?.Value;
            var subMenu = new List<LoginModel.SubMenu>();
            foreach (var item in site.Elements(node))
            {
                if (item.Attribute("roles") == null || item.Attribute("roles").Value.Contains(role))
                {
                    subMenu.Add(new LoginModel.SubMenu
                    {
                        Title = item.Attribute("title")?.Value,
                        Controller = item.Attribute("controller")?.Value,
                        Action = item.Attribute("action")?.Value,
                        Role = item.Attribute("roles")?.Value
                    });
                }
            }

            if (parentMenu != null)
            {
                dictionary.Add(parentMenu, subMenu);
            }
        }
    }*@
@{
    // Claims
    var claimsRoleList = User.FindFirst(ClaimTypes.Role)?.Value;

    var roles = string.Join(", ", claimsRoleList);

    // Sitemap
    const string node = "mvcSiteMapNode";

    var xElement = XElement.Load($"{Directory.GetCurrentDirectory()}/Sitemap.xml");
    var siteMap = from xml in xElement.Elements(node) select xml;
}

<div class="navbar-nav-wrap-content-left collapse navbar-collapse" id="navbarNavMenu">
    <div class="navbar-body">
        <ul class="navbar-nav flex-grow-1">
            @foreach (var site in siteMap)
            {
                var header = site.Attribute("mainTitle")?.Value;
                var icon = site.Attribute("icon")?.Value;
                <!-- Pages -->
                <li class="hs-has-sub-menu">
                    <a id="pagesDropdown" class="hs-mega-menu-invoker navbar-nav-link nav-link nav-link-toggle" href="javascript:;" aria-haspopup="true" aria-expanded="false" aria-labelledby="navLinkPagesDropdown-@header">
                        <i class="@icon nav-icon"></i> @header
                    </a>

                    <!-- Dropdown -->
                    <ul id="navLinkPagesDropdown-@header" class="hs-sub-menu dropdown-menu dropdown-menu-lg hs-sub-menu-desktop-lg animated" aria-labelledby="pagesDropdown-@header" style="min-width: 16rem; animation-duration: 300ms;">
                        @foreach (var item in site.Elements("mvcSiteMapSubTitle"))
                        {
                            var subTitle = item.Attribute("subTitle")?.Value;
                            var subMenuController = item.Attribute("controller")?.Value;
                            var subMenuAction = item.Attribute("action")?.Value;
                            @if (subMenuController != null)
                            {
                                <li>
                                    <a class="dropdown-item" href="@Url.Action(subMenuAction, subMenuController)">
                                        <span class="tio-circle nav-indicator-icon"></span> @subTitle
                                    </a>
                                </li>
                            }
                            else
                            {
                                <!-- Users -->
                                <li class="hs-has-sub-menu">
                                    <a id="pagesDropdownUsers-@subTitle" class="hs-mega-menu-invoker dropdown-item dropdown-item-toggle" href="javascript:;" aria-haspopup="true" aria-expanded="false" aria-controls="navLinkPagesDropdown-@subTitle-Users">
                                        <span class="tio-circle nav-indicator-icon"></span> @subTitle
                                    </a>

                                    <ul id="navLinkPagesDropdown-@subTitle-Users" class="hs-sub-menu dropdown-menu dropdown-menu-lg hs-sub-menu-desktop-lg animated" aria-labelledby="pagesDropdownUsers-@subTitle" style="min-width: 16rem; animation-duration: 300ms;">
                                        @foreach (var child in item.Elements("mvcSiteMapSubTitleChild"))
                                        {
                                            var childTitle = child.Attribute("childTitle")?.Value;
                                            var controller = child.Attribute("controller")?.Value;
                                            var action = child.Attribute("action")?.Value;

                                            <li>
                                                <a class="dropdown-item" href="@Url.Action(action, controller)">
                                                    <span class="tio-circle-outlined nav-indicator-icon"></span> @childTitle
                                                </a>
                                            </li>
                                            @*if (child.Attribute("roles") != null)
                                        {
                                            var occurrences = child.Attribute("roles").Value.Split(',').Select(s => s.Trim()).Intersect(roles.Split(',').Select(s => s.Trim()));
                                            if (occurrences.Count() > 0)
                                            {
                                                <li>
                                                    <a class="dropdown-item" href="@Url.Action(action, controller)">
                                                        <span class="tio-circle-outlined nav-indicator-icon"></span> @childTitle
                                                    </a>
                                                </li>
                                            }
                                        }
                                        else
                                        {
                                            <li>
                                                <a class="dropdown-item" href="@Url.Action(action, controller)">
                                                    <span class="tio-circle-outlined nav-indicator-icon"></span> @childTitle
                                                </a>
                                            </li>
                                        }*@
                                        }
                                    </ul>


                                </li>
                            }
                        }
                        <!-- End Users -->
                    </ul>
                    <!-- End Dropdown -->
                </li>
                <!-- End Pages -->
            }
            @if (User.IsInRole("Administrator"))
            {
            <!-- Pages -->
            <li class="hs-has-sub-menu">
                <a id="pagesDropdown" class="hs-mega-menu-invoker navbar-nav-link nav-link nav-link-toggle" href="javascript:;" aria-haspopup="true" aria-expanded="false" aria-labelledby="navLinkPagesDropdown-Users">
                    <i class="fas fa-user nav-icon"></i> Users
                </a>

                <!-- Dropdown -->
                <ul id="navLinkPagesDropdown-Users" class="hs-sub-menu dropdown-menu dropdown-menu-lg hs-sub-menu-desktop-lg animated" aria-labelledby="pagesDropdown-Users" style="min-width: 16rem; animation-duration: 300ms;">
                    <li>
                        <a class="dropdown-item" href="@Url.Action("ListUsers", "Admin")">
                            <span class="tio-circle-outlined nav-indicator-icon"></span> Overview
                        </a>
                    </li>
                    <!-- End Users -->
                </ul>
                <!-- End Dropdown -->
            </li>
            }
        </ul>
    </div>
</div>

Views/Shared/_LayoutUserPortal.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <!-- Required Meta Tags Always Come First -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title -->
    <title>Triton Business Online</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/favicon.ico">

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="~/front-dashboard-v1.1/dist/assets/css/vendor.min.css">
    <link rel="stylesheet" href="~/front-dashboard-v1.1/dist/assets/vendor/icon-set/style.css">

    <!-- CSS Front Template -->
    <link rel="stylesheet" href="~/front-dashboard-v1.1/dist/assets/css/theme.min.css?v=1.0">
</head>

<body class="d-flex align-items-center min-h-100">
    <!-- ========== HEADER ========== -->
    <header class="position-absolute top-0 left-0 right-0 mt-3 mx-3">
        <div class="d-flex d-lg-none justify-content-between">
            <span>
                <img src="~/front-dashboard-v1.1/dist/assets/img/logo/triton-logo.png" style="min-width: 7rem; max-width: 7rem;" alt=""/>
            </span>
        </div>
    </header>
    <!-- ========== END HEADER ========== -->
    <!-- ========== MAIN CONTENT ========== -->
    <main id="content" role="main" class="main pt-0">
        <!-- Content -->
        <div class="container-fluid px-3">
            <div class="row">
                <!-- Cover -->
                <div class="col-lg-6 d-none d-lg-flex justify-content-center align-items-center min-vh-lg-100 position-relative bg-light px-0">
                    <!-- Logo & Language -->
                    <div class="position-absolute top-0 left-0 right-0 mt-3 mx-3">
                        <div class="d-none d-lg-flex justify-content-between">
                            <span>
                                <img class="w-100" src="~/front-dashboard-v1.1/dist/assets/img/logo/triton-logo.png" alt="Image Description" style="min-width: 7rem; max-width: 7rem;">
                            </span>
                        </div>
                    </div>
                    <!-- End Logo & Language -->

                    <div style="max-width: 23rem;">
                        @*<div class="text-center mb-5">
                            <img class="img-fluid" src="~/front-dashboard-v1.1/dist/assets/svg/illustrations/chat.svg" alt="Image Description" style="width: 12rem;">
                        </div>*@

                        <div class="mb-5">
                            <h2 class="display-4 text-danger">signed.sealed.delivered</h2>
                        </div>

                        <!-- List Checked -->
                        <ul class="list-checked list-checked-lg list-checked-primary list-unstyled-py-4">
                            <li class="list-checked-item">
                                <span class="d-block font-weight-bold mb-1">T4 Express Road Freight</span>
                                Triton Express offers an overnight delivery service to most centres in South Africa, as well as a 48 hour service.
                            </li>

                            <li class="list-checked-item">
                                <span class="d-block font-weight-bold mb-1">T5 - Economy Road Freight</span>
                                Triton Express provides its customers with an economy road freight option with a 48 to 72 hour turnaround time for delivery at main centres.
                            </li>
                        </ul>
                        <!-- End List Checked -->

                        @*<div class="row justify-content-between mt-5 gx-2">
                            <div class="col">
                                <img class="img-fluid" src="~/front-dashboard-v1.1/dist/assets/svg/brands/gitlab-gray.svg" alt="Image Description">
                            </div>
                            <div class="col">
                                <img class="img-fluid" src="~/front-dashboard-v1.1/dist/assets/svg/brands/fitbit-gray.svg" alt="Image Description">
                            </div>
                            <div class="col">
                                <img class="img-fluid" src="~/front-dashboard-v1.1/dist/assets/svg/brands/flow-xo-gray.svg" alt="Image Description">
                            </div>
                            <div class="col">
                                <img class="img-fluid" src="~/front-dashboard-v1.1/dist/assets/svg/brands/layar-gray.svg" alt="Image Description">
                            </div>
                        </div>*@
                        <!-- End Row -->
                    </div>
                </div>
                <!-- End Cover -->

                @RenderBody()
            </div>
            <!-- End Row -->
        </div>
        <!-- End Content -->
    </main>
    <!-- ========== END MAIN CONTENT ========== -->
    <!-- JS Implementing Plugins -->
@*<script src="~/front-dashboard-v1.1/dist/assets/js/vendor.min.js"></script>*@
<script src="~/front-dashboard-v1.1/dist/assets/vendor/jquery/dist/jquery.min.js"></script>
<script src="~/front-dashboard-v1.1/dist/assets/vendor/jquery-migrate/dist/jquery-migrate.min.js"></script>
<script src="~/front-dashboard-v1.1/dist/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/front-dashboard-v1.1/dist/assets/vendor/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/front-dashboard-v1.1/dist/assets/js/theme.min.js"></script>

    <!-- JS Front -->
<script src="~/front-dashboard-v1.1/dist/assets/js/theme.min.js"></script>
<script src="~/front-dashboard-v1.1/dist/assets/vendor/hs-toggle-password/dist/js/hs-toggle-password.js"></script>
<script src="~/front-dashboard-v1.1/src/assets/js/hs.validation.min.js"></script>

    <!-- JS Plugins Init. -->
    <script>
        $(document).on('ready', function () {
            // INITIALIZATION OF SHOW PASSWORD
            // =======================================================
            $('.js-toggle-password').each(function () {
                new HSTogglePassword(this).init();
            });


            // INITIALIZATION OF FORM VALIDATION
            // =======================================================
            $('.js-validate').each(function () {
                $.HSCore.components.HSValidation.init($(this));
            });


            // INITIALIZATION OF SELECT2
            // =======================================================
            //$('.js-select2-custom').each(function () {
            //    var select2 = $.HSCore.components.HSSelect2.init($(this));
            //});
        });
    </script>

@await RenderSectionAsync("scripts", false)


<!-- IE Support -->
    <script>
    @{ var url = $"{Context.Request.PathBase}/front-dashboard-v1.1/dist/assets/vendor/babel-polyfill/polyfill.min.js"; }
    if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) document.write('<script src="@url"><\/script>');    </script>
</body>
</html>

Views/Shared/_RenderSearchScreenCard.cshtml
@{
    string title = this.ViewData.ContainsKey("TitleText") ? this.ViewData["TitleText"].ToString() : "Report";
    string titleSubText = this.ViewData.ContainsKey("TitleSubText") ? this.ViewData["TitleSubText"].ToString() : "Report information will be shown here";
}



    <div class="card">
        <div class="card-body">
            <!-- Hero Section -->
            <div class="container space-2">
                <div class="row justify-content-lg-between align-items-lg-center">
                    <div class="col-sm-10 col-lg-5 mb-7 mb-lg-0">
                        <img class="img-fluid" src="~/front-dashboard-v1.1/dist/assets/svg/illustrations/knowledgebase-community-1.svg" alt="Image Description" />
                    </div>

                    <div class="col-md-6">
                        <div class="mb-5">
                            <h1 class="display-4 mb-3">
                                @title
                                <br>
                                <span class="text-primary font-weight-bold">
                                    <span class="js-text-animation"></span>
                                </span>
                            </h1>
                            <p class="lead">@titleSubText</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Hero Section -->
        </div>
    </div>